plugins {
    id 'com.android.application'
}

android {
    namespace 'ir.tsgym.chat'
    compileSdk 35

    buildFeatures {
        buildConfig = true
    }

    signingConfigs {
        debug {
            storeFile file('keys/tsgymchat-debug.keystore')
            storePassword 'tsgymchatdebug'
            keyAlias 'tsgymchatdebug'
            keyPassword 'tsgymchatdebug'
        }
    }

    defaultConfig {
        applicationId 'ir.tsgym.chat'
        minSdk 24
        targetSdk 35
        versionCode 9
        versionName '4.0.0'
    }

    buildTypes {
        release {
            minifyEnabled true
            shrinkResources true
            proguardFiles getDefaultProguardFile('proguard-android-optimize.txt'), 'proguard-rules.pro'
        }
        debug {
            applicationIdSuffix '.debug'
            versionNameSuffix '-debug'
            signingConfig signingConfigs.debug
        }
    }

    compileOptions {
        sourceCompatibility JavaVersion.VERSION_17
        targetCompatibility JavaVersion.VERSION_17
    }
}
